#define auto auto 
#define dubbel double 
#define hel int 
#define strukt struct 
#define bryt break 
#define annars else 
#define lång long 
#define växla switch 
#define fall case 
#define uppräkning enum 
#define register register 
#define typdef typedef	
#define kar char 
#define extern extern 
#define returnera return 
#define union union 
#define fortsätt continue 
#define för for 
#define signerad signed 
#define tom void
#define gör do
#define om if
#define statisk static 
#define medan while
#define standard default
#define gåtill goto 
#define storlekav sizeof 
#define volatil volatile
#define konst const
#define flyt float
#define kort short
#define osignerad unsigned
